SampleSupervisor
Loop3D/map2loop pull request #101
Opened 2024-06-12 02:18 UTC by rabii-chaarani

## Description

- This is the new  SampleSupervisor class, it handles all storage and processing operations within Project() and outside of it. The class allow simple calls to get samples for any calculations.
- Various tests are added in this PR for  SampleSupervisor, the class passes all tests and works fine, if you have any other test cases to propose, please let me know. 
- It is expected that as we are adding more features over time, I will rewrite the SampleSupervisor in the future to use graphs to process the necessary computations in the correct order. 

Fixes #(issue)

## Type of change

- [ ] Documentation update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Test improvement

## How Has This Been Tested?

All tests performed are included in tests/sample_storage/test_sample_storage.py

## Checklist:

- [X] This branch is up-to-date with master
- [X] All gh-action checks are passing
- [X] I have performed a self-review of my own code
- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] My tests run with pytest from the map2loop folder
- [X] New and existing tests pass locally with my changes

## Checklist continued (if PR includes changes to documentation) 
- [ ] I have built the documentation locally with make.bat
- [ ] I have built this documentation in docker, following the docker configuration in map2loop/docs
- [ ] I have checked my spelling and grammar

2024-06-13 00:55 UTC, lachlangrose requested changes
There are a lot of changes in this pull request which make it a bit difficult to follow - I have left some comments on the code but I am not sure I follow the design/reasoning completely. I think it is important to think about how this class will interact with the other classes/methods within map2loop. I think a plan either as a design document and/or a flow chart would really help understanding these changes. 

When I initially suggested this class my intention was to have a class which has a `get_sample()` method for each different type of sample - it then either calls the appropriate sampler or returns the stored data depending on the current state. This would mean that within other samplers there could be a call to the sample_supervisor.get_samples for any other data type (although some care would be needed to prevent circular calls). The motivation behind this method was to allow for the underlying data or sampling algorithm parameters to be changed by the user and then map2loop would only recompute what was/is required. From what I could follow this current implementation does allow for this but the order of the calls is defined by the supervisor instead of the samplers - I think it would make more sense for the samplers to control the ordr because what is actually used by each sampler would be dependent on the algorithm.

I think that the calls to the project should not exists and these functions calculate_fault_orientations, summarise_fault_data, extract_geology_contacts should all be run by sampler type classes that are managed by this class. 

My last comment is there seem to some changes to m2l that are included in this pull request that are not really related to the sample supervisor. I know it is a pain to separate but it really makes reviewing the pull request easier if only the relevant changes are in the PR.

2024-06-13 00:55 UTC, lachlangrose commented on map2loop/sample_storage.py
> +class AccessStorage(ABC):
Is it really necessary to have an abstract class for this? I can't think of a case where there are multiple sample supervisors

2024-06-13 00:55 UTC, lachlangrose commented on map2loop/sample_storage.py
> +    def set_default_samplers(self):
Shouldn't default be chosen with appropriate parameterisation given the map/dataset?

2024-06-13 00:55 UTC, lachlangrose commented on map2loop/sample_storage.py
> +    def get_sampler(self, sampletype: SampleType):
Should this return the sample not the sample type? and it should be type hinted for the return type

2024-06-13 00:55 UTC, lachlangrose commented on map2loop/sample_storage.py
> +    def store(self, sampletype: SampleType, data):
What type is data? does this matter? Should there be any validation?

2024-06-13 00:55 UTC, lachlangrose commented on map2loop/sample_storage.py
> +            self.map_data.load_map_data(datatype)
I know this is from the mapdata class, but why can't we just have map_data.load(datatype)? And it takes care of what type the data is? Would probably be more future proof as raster data could also include geophysical grids

2024-06-13 00:55 UTC, lachlangrose commented on map2loop/sample_storage.py
> +        if sampletype == SampleType.CONTACT:
If the samplers are changed so that they have a `__call__` method this would avoid having to pass different arguments to the sample methods.

2024-06-13 00:55 UTC, lachlangrose commented on map2loop/sample_storage.py
> +                    self.map_data.basal_contacts, self.map_data
Why is basal contacts not an attribute of the sample supervisor? Isn't is something that is sampled?

2024-06-13 00:55 UTC, lachlangrose commented on map2loop/sample_storage.py
> +    def reprocess(self, sampletype: SampleType):
I don't really see why there is a reprocess. Shouldn't reprocess just be process?

2024-06-13 00:55 UTC, lachlangrose commented on map2loop/sample_storage.py
> +    def __call__(self, sampletype: SampleType):
I like having a call method, I think the logic is a bit complicated. It should just be self.process and return the data. All other checks should be done within process.

2024-06-14 00:36 UTC, rabii-chaarani commented
Rebasing did not solve the problem of having too many file changes. I will start over in another branch!

2025-01-05 22:36 UTC, closed without merging

2025-01-05 23:12 UTC, AngRodrigues commented
@rabii-chaarani, I was doing a branch clean up and this PR got automatically closed with the closure of 3.2. If you would like to re-open this, please change the branch you would like to merge to.